DELETE http://localhost:3003/api/blogs/5f6faf14855000232c41563e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbmlzaDEyNCIsImlkIjoiNWY2YjVkYzBhNGZjNDk1MDQ0ZDQ0Y2Y5IiwiaWF0IjoxNjAwODkxODYwfQ.cynOOaml4ykbsouw-FTyLhrzGVhhRV_rQ6cH71gkdZU